# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

# Fibonacci pattern is (starting from 2) even odd odd even...

# I don't really want to generate a huge list of big nums

total = 0
counter = 0 #counts number of steps to predict even numbers

max = 4000000

fibs = [1, 2]

while(fibs[1] <= max):
    if (counter % 3 == 0):
        total = total + fibs[1]

    counter = counter + 1
    placeholder = fibs[0] + fibs[1]
    fibs[0] = fibs[1]
    fibs[1] = placeholder


print(counter)
print(fibs)
print(total)